(ta-json) собственно добавил поддержку указанного Json
comdiv/golang_course_comdiv pull request #14
Opened 2021-06-12 21:21 UTC by comdiv

1.  Использовал `jsonparser` в итоге ни по памяти ни по скорости не просел на бенчмарках, не стал заменять поддержку плоских файлов - добавил еще одну опцию и вариант обработки в  то что было
2.  Подгтовил индекс "морально" к распаралелливанию - хотя пока и не стал использовать (нет ускорения если на вход 1 файл пока) - обеспечил операцию Merge у отдельных коллекций - чтобы можно было их собрать из разных файлов, а потом объединить.

При паралеллизме потом предполагаю обычный Map-Reduce - для каждого входного файла независимоя обработка с получением коллекции термов и на Reduce - их сведение (сделано так, что сводить можно в любом порядке, на важно с какой скоростью будет обработана какая часть и в каком порядке будет подаваться)

2021-06-12 21:28 UTC, comdiv commented on internal/textanalyzer/index/TermStatCollection.go
> +func CollectStatsFromJson(reader io.Reader, filter *TermFilter) *TermStatCollection {
Вот собственно поддержка JSON

2021-06-12 21:42 UTC, korjavin requested changes

2021-06-12 21:42 UTC, korjavin commented on internal/textanalyzer/index/TermStat.go
> +	l.lastCount = lastCount
Все таки getter/setter без доп. кода - редкая вещь

2021-06-12 21:42 UTC, korjavin commented on internal/textanalyzer/index/TermStat.go
> +	if l.firstPart == -1 || l.firstPart > part {
Нам текст подается разбитый по главам, нас просят вывести в порядке появления, в целом не просят "абсолютный номер".

Я бы ожидал что у нас появятся позиции в виде chapterNumber:Position что то такое. Тогда мы сможем упорядочить. Не претендуя что мы знаем реальный индекс.

Видимо firstPart это и есть глава?

Мне кажется тогда FullIndex да ещё публичный - может быть опасен.

Кто нибудь ещё поверит что там настоящее число.

2021-06-12 21:42 UTC, korjavin commented on internal/textanalyzer/main.go
> +		stats = index.CollectStatsFromJson(os.Stdin, filter)
Интересно, в этом месте я бы скорее пытался сохранить сигнатуру функции CollectStats, 
не дублировать её с FromJson 
а вот os.Stdin оборачивал бы в какой то reader который выдавал унифицированные reader

Т.е.  что то вроде
```
var reader chapterReader
if json {
  reader =myjson.Reader(io.stdin)
} else {
  reader =mytxt.Reader(io.stdin)
}
 		stats = index.CollectStats(os.Reader, filter)
 		
````

можно наверное порассуждать про плюсы минусы подходов.

Мне кажется что в моём варианте парсинг был бы изолирован. и я потом бы мог добавить protobuf или что то там ещё не меняя collectStat

}
```

2021-06-12 21:42 UTC, korjavin commented on internal/textanalyzer/testdata/main_test_json.json
> +    "text" : "Chapter two\n\n\tRhett Butler\n\n\tEarly the next morning, Gerald told his plantation manager, Jonas Wilkerson, to pack his things and leave. Jonas, Ellen had discovered, was the father
Рекомендую ` как кавычки для multiline

2021-06-12 21:42 UTC, korjavin commented on internal/textanalyzer/index/TermStatCollection.go
> +	for _, v := range other.Terms() {
Тут могу совет дать общий, не к этому коду, а в целом.

Если v большой, (структура например) то в каждой итерации цикла там будет копирование ( v этот локальный)

В этом случае помогает трюк
for i := range myslice {
  а тут работаем с myslice[i]
}

2021-06-12 21:46 UTC, comdiv commented on internal/textanalyzer/index/TermStat.go
> +	l.lastCount = lastCount
чисто в тестах понадобилось лень было конфиг объекты писать ))))

2021-06-12 21:48 UTC, comdiv commented on internal/textanalyzer/index/TermStat.go
> +	l.lastCount = lastCount
ну и нет привычки поля делать доступным, есть привычка всегда скрываать. Просто тут какая вещь. Если у меня было поле с именем X и все в него уже читали и писали (кто использовал структуру), а вдруг оказалось что так нельзя и надо именно через GetX() и SetX(), так как там логика какаято нужна - то переделать без последствий не получится - обратная совместимость теряется. А если сразу сделать на GetX() и SetX(), а само `X` скрыть в виде `x` пусть там и не делается ничего сверх чтения - присвоения, то это API структуры уже становится стойким. Поэтому рекомендую если класс сам не для приватного использования - всегда скрываать филды и выводит на акцессоры.

2021-06-12 21:50 UTC, comdiv commented on internal/textanalyzer/index/TermStat.go
> +	if l.firstPart == -1 || l.firstPart > part {
Наверное его стоит просто переименовать в GetSortIndex()

2021-06-12 21:54 UTC, korjavin commented on internal/textanalyzer/index/TermStat.go
> +	l.lastCount = lastCount
Привычка, вторая натура да. Но я тут поразмышлял, у меня их почти не бывает, я ка кто сильнее поля что ли прячу.

У меня скорее всего будет конструктор, и будет возможно какой то DoWork и ну может Opts
А setter/getter врядли.

В целом никакого запрета конечно нет, можно. Но вот есть конвенкция на имена.
Вот тут описана
https://golang.org/doc/effective_go#Getters

2021-06-12 21:55 UTC, comdiv commented on internal/textanalyzer/main.go
> +		stats = index.CollectStatsFromJson(os.Stdin, filter)
Не думаю что так. Тут вопрос не в подходе. У меня же может быть задача собрать статистику слов в JSON как таковом, например сколько раз встречается слово `hello` в JSON `{"hello": { "a" : "hello"} }` . Это первое. То есть мне надо четко указать коллектору что я имею в виду - индексацию плоского текста (в том числе и JSON) или именно индексацию JSON нужной схемы. При этом мне не нужны какие-то разные потоки для этого - я уже внутри их по-разному разложу.

Скорее тут напрашивался не `CollectStats` и `CollectStatsFromJson`, а `CollectStats(reader, MODE_PLAIN)` и `CollectStats(reader, MODE_JSON)` то есть - явное указание режима через параметр. Вот это наверное стоит потом пропатчить.

2021-06-12 21:55 UTC, korjavin commented on internal/textanalyzer/index/TermStat.go
> +	l.lastCount = lastCount
Это кстати хитрая конвенция, там есть второй смысл. Она и заставляет делать свойства с геттерами - приватными.

2021-06-12 21:56 UTC, comdiv commented on internal/textanalyzer/testdata/main_test_json.json
> +    "text" : "Chapter two\n\n\tRhett Butler\n\n\tEarly the next morning, Gerald told his plantation manager, Jonas Wilkerson, to pack his things and leave. Jonas, Ellen had discovered, was the father
Это же JSON документ ))))) в JSON такого нет....

2021-06-12 21:57 UTC, comdiv commented on internal/textanalyzer/index/TermStatCollection.go
> +	for _, v := range other.Terms() {
понял

2021-06-12 21:58 UTC, korjavin commented on internal/textanalyzer/testdata/main_test_json.json
> +    "text" : "Chapter two\n\n\tRhett Butler\n\n\tEarly the next morning, Gerald told his plantation manager, Jonas Wilkerson, to pack his things and leave. Jonas, Ellen had discovered, was the father
А, да, тут меня заглючило.  Я потому что в разрезе test case уже думал.

В частности из за того что  я выше там писал, я бы сам json parsing бы не тестил, а тестил типа как оно уже на структурах {number, text} себя ведет. Поэтому посмотрел на это как на go код.
Можно игнорировать

2021-06-15 22:13 UTC, korjavin approved these changes
Очень хорошо, но я предлагаю потренировать exactly N workers.

Но это к следующему разу.

2021-06-15 22:13 UTC, korjavin commented on internal/textanalyzer/index/TermStatCollection.go
> +		}(part, text)
Указатель на text помог бы тут с памятью?

2021-06-15 22:13 UTC, korjavin commented on internal/textanalyzer/index/TermStatCollection.go
> +	wg := new(sync.WaitGroup)
var wg sync.WaitGroup 
встречается чаще

2021-06-15 22:13 UTC, korjavin commented on internal/textanalyzer/index/TermStatCollection.go
> +	collected := make(chan struct{})
Навероное тут лучше wg

2021-06-17 18:03 UTC, merged