Проверка на "гонку" и прочее профиллирование
comdiv/golang_course_comdiv pull request #16
Opened 2021-06-20 15:39 UTC by comdiv

2021-06-20 20:56 UTC, korjavin approved these changes

2021-06-20 21:12 UTC, korjavin requested changes

2021-06-20 21:12 UTC, korjavin commented on Makefile
> +	## только не понял как SVG консольно сохранять в нужный файл
Под linux утилита tee часто используется

2021-06-20 21:12 UTC, korjavin commented on internal/textanalyzer/index/Stats_test.go
> +					panic(err)
В тестах хорошо использовать t.Fatal и прочие

2021-06-20 21:12 UTC, korjavin commented on internal/textanalyzer/index/TermStatCollection.go
> +		if processError != nil {
Всетаки параметр &processError я не могу принять.
В go не принято.

Можно например вернуть error changel 
и вместо for range одного, сделать например так
for  {
  select 
     case err:= <- errorCh:
     case data:= <- dataCh
   
}

2021-06-20 21:12 UTC, korjavin commented on internal/textanalyzer/tokens/tokenizerImpl.go
> +						wasOther = true
А здесь нельзя сразу break?

2021-06-20 21:12 UTC, korjavin commented on internal/textanalyzer/tokens/tokenizerImpl.go
> +						wasOther = true
Тут тоже break

2021-06-20 21:12 UTC, korjavin commented on internal/textanalyzer/tokens/Token.go
> +		result = strings.ToLower(result)
Если совсем уж упарываться, обе функции перебирают string, можно было наверное совместить.

2021-06-20 21:12 UTC, korjavin commented on internal/textanalyzer/tokens/tokenizerImpl.go
> +	t.token.isAscii = false
isAscii где нибудь дало прирост?

2021-06-21 01:29 UTC, comdiv commented on Makefile
> +	## только не понял как SVG консольно сохранять в нужный файл
На винде тоже никто в cmd не работает )) 
Но вы видимо уже увидели у меня по стилю - я люблю более рублено делать и разделять команды (типа defer в 2 функции, а не в одну) - тут та же история, я хочу явно выделить отдельную команду, которая явно со своим комментом в эхе выражает что она синхронит эти папки или файлы.

2021-06-21 01:31 UTC, comdiv commented on internal/textanalyzer/index/TermStatCollection.go
> +		if processError != nil {
Ну я по другому сделал, в более такой манере как мне кажется уместной в этом случае. Посмотрите.
У меня нет нужды как-то силььно обрабатывать ошибки, мне их важно не терять.

2021-06-21 01:32 UTC, comdiv commented on internal/textanalyzer/tokens/tokenizerImpl.go
> +						wasOther = true
Нет, потому что токены все возваращаются и слова и точки и прочее.
Разделение на предложения сдеално на уровне лексера. 
А тут все токены возвращаются

2021-06-21 01:32 UTC, comdiv commented on internal/textanalyzer/tokens/tokenizerImpl.go
> +						wasOther = true
Ответил выше

2021-06-21 01:34 UTC, comdiv commented on internal/textanalyzer/tokens/Token.go
> +		result = strings.ToLower(result)
Ну как сказать - мне просто эти проверки даются так сказать "из коробки" уже в токенайзере. Я на профайлере проверил - так чуточку но быстрее. Ну да, так-то разница невелика. Просто у меня в итоге есть заготовочка теоретическая если упороться свести все к понятию токен (укрупнив засчет лексемы) и в нем больше обработок делать (если флаги включены) и там скорее всего еще %20 где-то выиграется времени/памяти, но пока не парился

2021-06-21 01:36 UTC, comdiv commented on internal/textanalyzer/tokens/tokenizerImpl.go
> +	t.token.isAscii = false
Да дает, там где проверяется тип токена. Слово это, или непонятно что. Если isAscii я работаю только с байтами и не проверяю разных алфавитов в словах, а если нет - то с рунами приходится работать и там еще русский проверяется

2021-06-21 08:03 UTC, korjavin approved these changes

2021-06-21 08:54 UTC, merged